### ISSUE TITLE
Issues in 17.1.x

### ISSUE THREAD

**Issue by vimarx** [jnm2/DevExpressMods#21]
Alfter upgrading to 17.1 I'm havving issues with reports using DevExpressMods (XAF)

please see
https://www.screencast.com/t/EAqMBllRU60O

**Comment by jnm2** [comment]
Yes, an update is due here. I also have a better design in version 2 which I need to move here. Thanks for speaking up; otherwise there's no way for me to tell if people are using DevExpressMods. :smile:

**Comment by vimarx** [comment]
Thanks, do you have an estimate date for your update?

**Comment by jnm2** [comment]
I already have a fix for the particular error you showed in the screencast. Thanks for that by the way!
I'll work on getting a release out this weekend.

**Comment by jnm2** [comment]
Ran into some logistical issues, but the release is now ready at https://www.nuget.org/packages/DevExpressMods/1.1.0.
