### ISSUE TITLE
not compiling in 17.2.3 hotfix 17.2.3.331+

### ISSUE THREAD

**Issue by vimarx** [jnm2/DevExpressMods#22]

**Comment by jnm2** [comment]
With the appearance of expression bindings, my next goal is to deprecate this project. See #23.

A 17.2 release is central to that strategy so that reports with SummaryFields can be edited in 17.2 as they are converted to use expression bindings instead.

**Comment by jnm2** [comment]
They've broken all implementers of IColumnImageProvider in the latest hotfixes. I'm going to confirm whether they intend to keep it broken for 17.2.4.

**Comment by jnm2** [comment]
The latest hotfixes have broken all implementers of IColumnImageProviders. I'm going to confirm whether they intend to keep it broken for 17.2.4. (See https://www.devexpress.com/Support/Center/Question/Details/T583283.)

**Comment by jnm2** [comment]
Fixed in https://github.com/jnm2/DevExpressMods/commit/df9847c2177e6fded17ce14cfc990511d14326e2.

There is a new release available at https://www.nuget.org/packages/DevExpressMods/1.3.0 with this fix.
