### ISSUE TITLE
Create demo applications

### ISSUE THREAD

**Issue by jnm2** [jnm2/DevExpressMods#8]
Probably the only barrier to entry for people is the lack of sample code.

https://github.com/jnm2/DevExpressMods#getting-started has instructions but nothing beats seeing it in action.
- [x] Create a XAF report designer demo (#10)
- [ ] Create a WinForms ReportDesignTool-based demo (standard and ribbon)
- [ ] Create a WinForms custom designer demo (standard and ribbon)
- [ ] Link samples from the readme and remove ModdedEndUserDesigner.cs

**Comment by RascoApps** [comment]
Could you create the Demo Application from the XAF XRM Demo?
If you have DevExpress Universal, it can be found at: 
C:\Users\Public\Documents\DevExpress Demos 16.1\Components\eXpressApp Framework\XCRM\CS

Then just follow the article to get access to the Mdi Controller: [How to: Customize the WinForms Report Designer Form](https://documentation.devexpress.com/#eXpressAppFramework/CustomDocument113604)

I basically followed this on our solution, but the context menu item did not show without throwing any exceptions. I traced through the code but it all seems correct.

**Comment by jnm2** [comment]
Following up from our Gitter conversation. Yes, that is now complete at https://github.com/jnm2/DevExpressMods/blob/master/Samples/eXpressApp%20XCRM/Walkthrough.md.

**Comment by jnm2** [comment]
With the appearance of expression bindings, my next goal is to deprecate this project. See #23.
